export const REAL_TEAM_DATABASE = [
  { region: 'Americas', name: '100Thieves', coach: 'Nbs', roster: ['Cryocells|Sentinel|Oper', 'Vora|Initiator|IGL', 'Asuna|Flex', 'Timotino|Duelist|Entry', 'Bang|Controller'] },
  { region: 'Americas', name: 'Cloud9', coach: 'Immi', roster: ['Zellsis|Initiator|IGL', 'Penny|Duelist', 'Xeppaa|Initiator', 'OXY|Duelist|Oper', 'v1c|Controller'] },
  { region: 'Americas', name: 'Evil Geniuses', coach: 'potter', roster: ['dgz|Duelist|Oper', 'Okeanos|Flex|Entry', 'bao|Sentinel', 'supamen|Controller', 'C0M|Initiator|IGL'] },
  { region: 'Americas', name: 'FURIA', coach: 'shaW', roster: ['artzin|Controller|IGL', 'koalanoob|Duelist/Flex|Oper', 'alym|Duelist|Entry', 'nerve|Initiator/Flex', 'eeiu|Initiator', 'Basic|Initiator|Bench'] },
  { region: 'Americas', name: 'KRÜ Esports', coach: 'ZONYK', roster: ['Less|Sentinel', 'saadhak|Initiator|IGL', 'mwzera|Initiator/Flex', 'dantedeu5|Duelist', 'silentzz|Controller'] },
  { region: 'Americas', name: 'LEVIATÁN', coach: 'Onur', roster: ['spike|Flex/Initiator', 'Neon|Duelist/Sentinel|Oper', 'Sato|Duelist|Entry', 'kiNgg|Controller|IGL', 'blowz|Initiator'] },
  { region: 'Americas', name: 'LOUD', coach: 'Romanilly', roster: ['cauanzin|Initiator|IGL', 'erde|Controller/Flex', 'lukxo|Sentinel/Duelist', 'Darker|Initiator/Flex', 'pANcada|Controller|IGL'] },
  { region: 'Americas', name: 'MIBR', coach: 'fRoD', roster: ['Aspas|Duelist|Oper', 'Zekken|Duelist/Controller|Entry', 'Verno|Initiator|IGL', 'tex|Sentinel', 'Mazino|Flex'] },
  { region: 'Americas', name: 'NRG', coach: 'bonkar', roster: ['Mada|Duelist|Oper', 'Skuba|Sentinel', 'brawk|Initiator', 'keiko|Controller/Flex', 'Ethan|Initiator|IGL'] },
  { region: 'Americas', name: 'Sentinels', coach: 'kaplan', roster: ['Cortezia|Sentinel', 'N4RRATE|Duelist|Oper', 'Reduxx|Duelist', 'Kyu|Initiator|IGL', 'johnqt|Controller'] },
  { region: 'Americas', name: 'G2 Esports', coach: 'JoshRT', roster: ['valyn|Controller|IGL', 'jawgemo|Duelist|Entry', 'BABYBAY|Duelist/Sentinel', 'trent|Initiator', 'leaf|Sentinel/Flex'] },
  { region: 'Americas', name: 'ENVY', coach: 'Stunner', roster: ['Rossy|Controller', 'P0PPIN|Initiator|IGL', 'keznit|Duelist', 'Eggster|Duelist', 'Demon1|Sentinel|Oper'] },

  { region: 'EMEA', name: 'BBL Esports', coach: 'KEY', roster: ['lovers rock|Duelist', 'Lar0k|Duelist', 'Rosé|Initiator|IGL', 'Crewen|Sentinel', 'Loita|Controller'] },
  { region: 'EMEA', name: 'FNATIC', coach: 'Milan', roster: ['Alfajer|Sentinel/Duelist', 'Veqaj|Flex/Initiator', 'Crashies|Initiator', 'Boaster|Controller|IGL', 'kaajak|Duelist'] },
  { region: 'EMEA', name: 'FUT Esports', coach: 'Gais', roster: ['MrFaliN|Flex/Controller', 'yetujey|Duelist/Sentinel|IGL', 'baha|Controller', 'KROSTALY|Initiator', 'xeus|Duelist'] },
  { region: 'EMEA', name: 'Gentle Mates', coach: 'pakko', roster: ['marteen|Duelist', 'Minny|Sentinel/Controller', 'bipo|Duelist', 'GLYPH|Controller', 'starxo|Initiator|IGL'] },
  { region: 'EMEA', name: 'GIANTX', coach: 'pipsoN', roster: ['Flickless|Flex', 'grubinho|Controller', 'westside|Sentinel', 'Cloud|Initiator|IGL', 'ara|Duelist'] },
  { region: 'EMEA', name: 'Karmine Corp', coach: 'ENGH', roster: ['SUYGETSU|Controller/Sentinel', 'dos9|Controller', 'Sheydos|Initiator|IGL', 'Avez|Flex/Initiator', 'LewN|Duelist'] },
  { region: 'EMEA', name: 'Natus Vincere', coach: 'ANGE1', roster: ['hiro|Initiator/Flex', 'Ruxic|Sentinel', 'sociablEE|Initiator/Flex|IGL', 'Filu|Duelist', 'Shao|Controller'] },
  { region: 'EMEA', name: 'Team Heretics', coach: 'neilzinho', roster: ['Boo|Controller|IGL', 'ComeBack|Duelist', 'benjyfishy|Sentinel', 'wo0t|Duelist/Flex', 'RieNs|Initiator'] },
  { region: 'EMEA', name: 'Team Liquid', coach: 'LohaN', roster: ['nAts|Sentinel/Controller|IGL', 'Kicks|Controller', 'Miniboo|Duelist', 'kamo|Initiator', 'purp0|Duelist/Flex'] },
  { region: 'EMEA', name: 'Team Vitality', coach: 'PAL', roster: ['Derke|Duelist', 'Chronicle|Sentinel', 'PROFEK|Controller', 'Jamppi|Flex|IGL', 'UNFAKE|Initiator', 'Sayonara|Duelist|Bench'] },
  { region: 'EMEA', name: 'ULF Esports', coach: 'afr0nfire', roster: ['audaz|Controller', 'Favian|Flex', 'nekky|Initiator|IGL', 'sturNN|Controller/Flex', 'd3mur|Duelist'] },
  { region: 'EMEA', name: 'PCIFIC Esports', coach: 'thinkii', roster: ['seven|Flex', 'cNed|Duelist', 'NINJA|Initiator', 'qpert|Controller|IGL', 'al0rante|Sentinel'] },

  { region: 'China', name: 'All Gamers', coach: 'ED101', roster: ['f4ngeer|Duelist', 'Au1|Sentinel', 'K1ra|Flex|IGL', 'Shr1mp|Initiator', 'iamgrq|Controller/Flex'] },
  { region: 'China', name: 'Bilibili Gaming', coach: 'Muggle', roster: ['nephh|Controller/Initiator|IGL', 'Knight|Initiator', 'whzy|Duelist', 'rushia|Controller', 'bud|Initiator'] },
  { region: 'China', name: 'EDward Gaming', coach: 'Autumn', roster: ['nobody|Initiator|IGL', 'CHICHOO|Sentinel', 'Smoggy|Controller', 'ZmjjKK|Duelist|Oper', 'cb|Duelist'] },
  { region: 'China', name: 'FunPlus Pheonix', coach: 'LEGIJA', roster: ['Setrod|Duelist/Flex', 'sScary|Controller', 'AAAAY|Sentinel', 'Life|Duelist', 'BerLIN|Initiator|IGL'] },
  { region: 'China', name: 'JDG Esports', coach: 'bail', roster: ['jkuro|Controller', 'Yuicaw|Sentinel', 'zhe|Duelist', 'coconut|Initiator|IGL', 'stew|Duelist'] },
  { region: 'China', name: 'Nova Esports', coach: 'pr', roster: ['heybay|Initiator|IGL', 'GREEN|Flex/Duelist', 'GuanG|Duelist', 'Ezeir|Initiator/Sentinel', 'OBONE|Controller'] },
  { region: 'China', name: 'Titan Esports', coach: 'AfteR', roster: ['Abo|Duelist/Flex', 'lucas|Initiator|IGL', 'Coco|Sentinel', 'Dynamite|Duelist', 'Haodong|Controller'] },
  { region: 'China', name: 'Trace Esports', coach: 'destroyeR', roster: ['deLb|Sentinel', 'FengF|Initiator', 'Viva|Initiator', 'Kai|Duelist', 'LuoK1ng|Controller'] },
  { region: 'China', name: 'TYLOO', coach: 'hyponotizing', roster: ['splash|Duelist', 'slowly|Duelist', 'Erv|Controller', 'Scales|Sentinel', 'sword9|Initiator|IGL'] },
  { region: 'China', name: 'Wolves Esports', coach: 'Fayde', roster: ['SiuFatBB|Initiator|IGL', 'jowa|Controller', 'qiutiaN|Duelist', 'yosemite|Sentinel', 'Spring|Duelist/Flex'] },
  { region: 'China', name: 'Xi Lai Gaming', coach: 'hvoya', roster: ['happywei|Controller/Sentinel', 'Lysoar|Controller|IGL', 'Rarga|Duelist', 'NoMan|Duelist', 'WsLeo|Initiator'] },
  { region: 'China', name: 'Dragon Ranger Gaming', coach: 'NaThanD', roster: ['vo0kashu|Sentinel', 'SpiritZ1|Duelist', 'Akeman|Duelist', 'Flex1n|Controller', 'Nicc|Initiator|IGL'] },

  { region: 'Pacific', name: 'DetonatioN FocusMe', coach: 'Vorz', roster: ['Caedye|Sentinel', 'SSeeS|Controller', 'Meiy|Duelist', 'Akame|Initiator|IGL', 'yatsuka|Duelist'] },
  { region: 'Pacific', name: 'DRX', coach: 'termi', roster: ['free1ng|Flex', 'MaKo|Controller', 'BeYN|Initiator|IGL', 'Hermes|Duelist', 'HYUNMIN|Duelist'] },
  { region: 'Pacific', name: 'FULL SENSE', coach: 'Crws', roster: ['primmie|Duelist', 'Killua|Initiator', 'Leviathan|Controller', 'JitBoyS|Sentinel|IGL', 'thyy|Duelist'] },
  { region: 'Pacific', name: 'Gen.G', coach: 'solo', roster: ['Ash|Controller', 'Karon|Sentinel', 't3xture|Duelist', 'ZynX|Duelist', 'Lakia|Initiator|IGL'] },
  { region: 'Pacific', name: 'Global Esports', coach: 'FrosT', roster: ['UdoTan|Sentinel', 'PatMen|Controller/Flex', 'xavi8k|Controller', 'Kr1stal|Initiator|IGL', 'Autumn|Duelist'] },
  { region: 'Pacific', name: 'Paper Rex', coach: 'alecks', roster: ['f0rsakeN|Controller', 'Jinggg|Duelist', 'something|Duelist', 'invy|Initiator', 'd4v41|Sentinel|IGL'] },
  { region: 'Pacific', name: 'Rex Regum Qeon', coach: 'Jovi', roster: ['Kushy|Initiator|IGL', 'xffero|Sentinel', 'Jemkin|Duelist', 'crazyguy|Controller', 'Monyet|Duelist'] },
  { region: 'Pacific', name: 'T1', coach: 'KDG', roster: ['BuZz|Duelist', 'iZu|Duelist', 'stax|Initiator|IGL', 'Munchkin|Controller', 'Meteor|Sentinel'] },
  { region: 'Pacific', name: 'Team Secret', coach: 'Rbtx', roster: ['BerserX|Sentinel', 'kellyS|Duelist', 'Sylvan|Controller', 'JessieVash|Initiator|IGL', 'TenTen|Duelist'] },
  { region: 'Pacific', name: 'ZETA DIVISION', coach: 'XQQ', roster: ['eKo|Duelist', 'Absol|Duelist', 'SugarZ3ro|Controller|IGL', 'Syouta|Sentinel', 'Xdll|Initiator'] },
  { region: 'Pacific', name: 'VARREL', coach: 'TK9', roster: ['Zexy|Duelist', 'Klaus|Duelist/Flex', 'XuNa|Initiator|IGL', 'oonzmlp|Sentinel', 'C1ndeR|Controller'] },
  { region: 'Pacific', name: 'Nongshim RedForce', coach: 'SilKanoN', roster: ['Dambi|Duelist', 'Rb|Controller|IGL', 'Francis|Duelist', 'Xross|Initiator', 'Ivy|Sentinel'] }
];
